[connections.api_reverse_crawler]
    type="sql"
    dialect="postgresql"
    username="postgres"
    password="postgres"
    host="pc-work.tail3af31.ts.net" # IP or URL
    port=5432 # Port number
    database="api_reverse_crawler_v1" # Database name